### ISSUE TITLE
Capistrano script

### ISSUE THREAD

**Issue by diegoamc** [mezuro/kalibro_processor#101]
We have to improve our deploy process to add the new features available for capistrano 3.4.0, as the creation of symbolic links with a better sintax than we have now.

Also, we have to guarantee that the workers from DelayedJobs are restarted after the deploy. It seems that they keep running the old code, which can lead to inconsistencies.

**Comment by rafamanzo** [comment]
https://github.com/capistrano/passenger/ looks nice as well :)

**Comment by rafamanzo** [comment]
Duplicate with https://github.com/mezuro/kalibro_processor/issues/119
