### ISSUE TITLE
Handle invalid URLs for Downloader::Git

### ISSUE THREAD

**Issue by rafamanzo** [mezuro/kalibro_processor#109]
If the URL is invalid, ls-remote will ask for user and password.

**Comment by danielkza** [comment]
I thought that was already fixed by settiing the GIT_ASKPASS environment variable. Do you have an example of one URL that breaks things?

**Comment by rafamanzo** [comment]
So it was actually fixed. I forgot about this modification and this was one of our code quality post-its. Thanks!
