### ISSUE TITLE
Radon collector creates duplicated MetricResults

### ISSUE THREAD

**Issue by danielkza** [mezuro/kalibro_processor#133]
I found out while attempting to finish the HotspotMetrics that the Radon collector generates MetricResults with duplicate sets of (module_result_id, metric_configuration_id) for methods that have the same name, such as getters and setters (since their decorators change their names inside the interpreter, but Radon doesn't actually run one).

We need to fix that, and probably create an unique index in the database to prevent any further cases like that.

**Comment by rafamanzo** [comment]
- [ ] Validate `KalibroModule` `long_name` uniqueness within `processin_id` (notice that this validation is indirect through `ModuleResult`
- [ ] Validate `MetricResult` `metric_configuration_id` within `module_result_id` scope
- [ ] Check if everything still works ( those validations may rise some silent fails that have been happening for some time)
