### ISSUE TITLE
Refactor parsers

### ISSUE THREAD

**Issue by diegoamc** [mezuro/kalibro_processor#144]
With the growing number of collectors, it is possible that some code is duplicated and could be extracted to other classes, improving maintainability.

**Comment by rafamanzo** [comment]
From flay code analysis we get:

- [ ] `radon/parser/base` and `metric_fu/parser/base` have duplications
- [ ] `radon/collector` and `metric_fu/collector`

This list may be bigger.

work in progress on the branch `parser_refactor`

**Comment by danielkza** [comment]
This is  being  implemented through [Kolekti](/mezuro/kolekti). We now need to refactor Radon and MetricFu.

**Comment by danielkza** [comment]
This was finalized with #196. There are no more collectors directly implemented in kalibro_processor.
