### ISSUE TITLE
Wrong Granularity conversion to JSON

### ISSUE THREAD

**Issue by rafamanzo** [mezuro/kalibro_processor#166]
As of https://lists.ime.usp.br/archives/mezuro-core/2016-January/006649.html there is a not yet known case where KalibroModule's Granularity conversion to JSON outputs `{:type => CLASS}` which is inconsistent with other cases where it outputs just `'CLASS'`.

We need to narrow which run path produces this and decide which standard is the correct one.

**Comment by danielkza** [comment]
See mezuro/kalibro_client#90, mezuro/kalibro_client#91, mezuro/kalibro_configurations#72.
