### ISSUE TITLE
Create acceptance test for ModuleResult retrieval with Hotspot results

### ISSUE THREAD

**Issue by rafamanzo** [mezuro/kalibro_processor#216]
We once thought we had this covered (fa7b986) but figured out it was working because of inner bugs (https://github.com/mezuro/kalibro_processor/pull/214#discussion_r71339138).

We have to create a new acceptance test that covers this.

**Comment by danielkza** [comment]
I think changing the step to check for the first descendant hotspot metric result from the root should fix it. It doesn't matter which result we use, as long as we can find one.
