### ISSUE TITLE
repositories_of methods with project_id

### ISSUE THREAD

**Issue by rafamanzo** [mezuro/kalibro_processor#48]
Would be useful to have the project_id returned inside the repositories after calling the repositories_of method.

I know that if you called repositories_of you do know the project_id, but the result to this call will get to other contexts where we don't know the project_id.

I think the root of this problem is the lack of a find method for Repository. Which is implemented on the KalibroEntities gem by getting all the projects on the service and then calling repositoies_of for each project, so finally we can search this list of all the repositories for the one that we're looking for.

So this feature is useful as long as Repository doesn't have a find method.

**Comment by DylanGuedes** [comment]
The desired behaviour is a response with the repositories and the project_id (w/o nesting) like:
 `{ repositories: [], project_id: X}`
 or nesting the project_id for every repository like:
`repositories: [{repository: repositoryA, project_id: X}]`
?

I'll create a PR with the first behaviour, but if the correct is the second let me know.

**Comment by rafamanzo** [comment]
Do you have another user case for this information?

Because unfortunately `Repository` did got a find method back in https://github.com/mezuro/kalibro_client/commit/d53d8495fbcddf268846d012707d34890149236b. Thus as mentioned in the description, this modification might not be necessary anymore.

What do you think?

**Comment by DylanGuedes** [comment]
To be fair I think that this addition is unnecesary. I'll close th
